# SkyGrid 配置文件 ${version}
#
skygrid:
  command:
    # 天空网指令.
    # 要定义多个指令, 请用空格分隔.
    island: skygrid sg
    # 天空网管理员指令.
    # 要定义多个管理员指令, 请用空格分隔.
    admin: sgadmin sga
world:
  chest-fill:
    # 每个主世界箱子中有多少种物品
    overworld: 5
    # 每个下界箱子中有多少种物品
    nether: 5
    # 每个末地箱子中有多少种物品
    end: 5
  # 箱子中可以出现的物品. 每种物品出现的概率相同.
  chest-items:
    overworld:
    - ACTIVATOR_RAIL
    - ANVIL
    - APPLE
    - ARMOR_STAND
    - ARROW
    - BAKED_POTATO
    - BAMBOO_SAPLING
    - BARREL
    - BAT_SPAWN_EGG
    - BEACON
    - BEEF
    - BEETROOT_SEEDS
    - BEETROOT_SOUP
    - BELL
    - BLACK_BANNER
    - BLACK_BED
    - BLACK_DYE
    - BLAST_FURNACE
    - BLAZE_ROD
    - BLUE_BANNER
    - BLUE_BED
    - BLUE_DYE
    - BLUE_ICE
    - BLUE_WOOL
    - BONE
    - BONE_BLOCK
    - BONE_MEAL
    - BOOK
    - BOOKSHELF
    - BOW
    - BOWL
    - BREAD
    - BREWING_STAND
    - BRICK
    - BRICK_WALL
    - BRICKS
    - BROWN_BANNER
    - BROWN_BED
    - BROWN_DYE
    - BROWN_MUSHROOM
    - BROWN_WOOL
    - BUCKET
    - CACTUS
    - CAKE
    - CAMPFIRE
    - CARROT
    - CARROT_ON_A_STICK
    - CARTOGRAPHY_TABLE
    - CARVED_PUMPKIN
    - CAT_SPAWN_EGG
    - CAULDRON
    - CAVE_SPIDER_SPAWN_EGG
    - CHAINMAIL_BOOTS
    - CHAINMAIL_CHESTPLATE
    - CHAINMAIL_HELMET
    - CHAINMAIL_LEGGINGS
    - CHARCOAL
    - CHEST_MINECART
    - CHICKEN
    - CHICKEN_SPAWN_EGG
    - CHISELED_RED_SANDSTONE
    - CHISELED_SANDSTONE
    - CHISELED_STONE_BRICKS
    - CLAY
    - CLAY_BALL
    - CLOCK
    - COAL
    - COAL_BLOCK
    - COAL_ORE
    - COARSE_DIRT
    - COCOA
    - COCOA_BEANS
    - COD
    - COD_BUCKET
    - COD_SPAWN_EGG
    - COMPARATOR
    - COMPASS
    - COMPOSTER
    - CONDUIT
    - COOKED_BEEF
    - COOKED_CHICKEN
    - COOKED_COD
    - COOKED_MUTTON
    - COOKED_PORKCHOP
    - COOKED_RABBIT
    - COOKED_SALMON
    - COOKIE
    - CORNFLOWER
    - COW_SPAWN_EGG
    - CRAFTING_TABLE
    - CREEPER_BANNER_PATTERN
    - CREEPER_SPAWN_EGG
    - CROSSBOW
    - CUT_RED_SANDSTONE
    - CUT_RED_SANDSTONE_SLAB
    - CUT_SANDSTONE
    - CUT_SANDSTONE_SLAB
    - CYAN_BANNER
    - CYAN_BED
    - CYAN_DYE
    - CYAN_WOOL
    - DARK_PRISMARINE
    - DAYLIGHT_DETECTOR
    - DETECTOR_RAIL
    - DIAMOND
    - DIAMOND_AXE
    - DIAMOND_BLOCK
    - DIAMOND_BOOTS
    - DIAMOND_CHESTPLATE
    - DIAMOND_HELMET
    - DIAMOND_HOE
    - DIAMOND_LEGGINGS
    - DIAMOND_ORE
    - DIAMOND_PICKAXE
    - DIAMOND_SHOVEL
    - DIAMOND_SWORD
    - DISPENSER
    - DOLPHIN_SPAWN_EGG
    - DONKEY_SPAWN_EGG
    - DRIED_KELP
    - DRIED_KELP_BLOCK
    - DROPPER
    - DROWNED_SPAWN_EGG
    - EGG
    - ELDER_GUARDIAN_SPAWN_EGG
    - EMERALD
    - EMERALD_BLOCK
    - EMERALD_ORE
    - ENCHANTED_BOOK
    - ENCHANTED_GOLDEN_APPLE
    - ENCHANTING_TABLE
    - ENDER_PEARL
    - EVOKER_SPAWN_EGG
    - EXPERIENCE_BOTTLE
    - FEATHER
    - FERMENTED_SPIDER_EYE
    - FERN
    - FIRE
    - FIRE_CHARGE
    - FIREWORK_ROCKET
    - FIREWORK_STAR
    - FISHING_ROD
    - FLETCHING_TABLE
    - FLINT
    - FLINT_AND_STEEL
    - FLOWER_BANNER_PATTERN
    - FLOWER_POT
    - FOX_SPAWN_EGG
    - FURNACE
    - FURNACE_MINECART
    - GHAST_SPAWN_EGG
    - GHAST_TEAR
    - GLISTERING_MELON_SLICE
    - GLOBE_BANNER_PATTERN
    - GLOWSTONE
    - GLOWSTONE_DUST
    - GOLD_BLOCK
    - GOLD_INGOT
    - GOLD_NUGGET
    - GOLD_ORE
    - GOLDEN_APPLE
    - GOLDEN_AXE
    - GOLDEN_BOOTS
    - GOLDEN_CARROT
    - GOLDEN_CHESTPLATE
    - GOLDEN_HELMET
    - GOLDEN_HOE
    - GOLDEN_HORSE_ARMOR
    - GOLDEN_LEGGINGS
    - GOLDEN_PICKAXE
    - GOLDEN_SHOVEL
    - GOLDEN_SWORD
    - GRAVEL
    - GRAY_BANNER
    - GRAY_BED
    - GRAY_DYE
    - GREEN_BANNER
    - GREEN_BED
    - GREEN_DYE
    - GRINDSTONE
    - GUARDIAN_SPAWN_EGG
    - GUNPOWDER
    - HAY_BLOCK
    - HEART_OF_THE_SEA
    - HEAVY_WEIGHTED_PRESSURE_PLATE
    - HOPPER
    - HOPPER_MINECART
    - HORSE_SPAWN_EGG
    - HUSK_SPAWN_EGG
    - ICE
    - INK_SAC
    - IRON_AXE
    - IRON_BARS
    - IRON_BLOCK
    - IRON_BOOTS
    - IRON_CHESTPLATE
    - IRON_DOOR
    - IRON_HELMET
    - IRON_HOE
    - IRON_HORSE_ARMOR
    - IRON_INGOT
    - IRON_LEGGINGS
    - IRON_NUGGET
    - IRON_ORE
    - IRON_PICKAXE
    - IRON_SHOVEL
    - IRON_SWORD
    - IRON_TRAPDOOR
    - ITEM_FRAME
    - JACK_O_LANTERN
    - JUKEBOX
    - KELP
    - KELP_PLANT
    - LADDER
    - LANTERN
    - LAPIS_BLOCK
    - LAPIS_LAZULI
    - LAPIS_ORE
    - LARGE_FERN
    - LAVA_BUCKET
    - LEAD
    - LEATHER
    - LEATHER_BOOTS
    - LEATHER_CHESTPLATE
    - LEATHER_HELMET
    - LEATHER_HORSE_ARMOR
    - LEATHER_LEGGINGS
    - LECTERN
    - LEVER
    - LIGHT_BLUE_BANNER
    - LIGHT_BLUE_BED
    - LIGHT_BLUE_DYE
    - LIGHT_GRAY_BANNER
    - LIGHT_GRAY_BED
    - LIGHT_GRAY_DYE
    - LIGHT_GRAY_WOOL
    - LIGHT_WEIGHTED_PRESSURE_PLATE
    - LILAC
    - LILY_OF_THE_VALLEY
    - LILY_PAD
    - LIME_BANNER
    - LIME_BED
    - LIME_CARPET
    - LIME_DYE
    - LIME_WOOL
    - LLAMA_SPAWN_EGG
    - LOOM
    - MAGENTA_BANNER
    - MAGENTA_BED
    - MAGENTA_DYE
    - MAGENTA_WOOL
    - MAGMA_BLOCK
    - MAGMA_CREAM
    - MAGMA_CUBE_SPAWN_EGG
    - MAP
    - MELON
    - MELON_SEEDS
    - MELON_SLICE
    - MILK_BUCKET
    - MINECART
    - MOJANG_BANNER_PATTERN
    - MOOSHROOM_SPAWN_EGG
    - MULE_SPAWN_EGG
    - MUSHROOM_STEW
    - MUSIC_DISC_11
    - MUSIC_DISC_13
    - MUSIC_DISC_BLOCKS
    - MUSIC_DISC_CAT
    - MUSIC_DISC_CHIRP
    - MUSIC_DISC_FAR
    - MUSIC_DISC_MALL
    - MUSIC_DISC_MELLOHI
    - MUSIC_DISC_STAL
    - MUSIC_DISC_STRAD
    - MUSIC_DISC_WAIT
    - MUSIC_DISC_WARD
    - MUTTON
    - MYCELIUM
    - NAME_TAG
    - NAUTILUS_SHELL
    - NOTE_BLOCK
    - OBSERVER
    - OBSIDIAN
    - OCELOT_SPAWN_EGG
    - ORANGE_BANNER
    - ORANGE_BED
    - ORANGE_DYE
    - ORANGE_TULIP
    - ORANGE_WOOL
    - OXEYE_DAISY
    - PACKED_ICE
    - PAINTING
    - PANDA_SPAWN_EGG
    - PAPER
    - PARROT_SPAWN_EGG
    - PEONY
    - PETRIFIED_OAK_SLAB
    - PHANTOM_MEMBRANE
    - PHANTOM_SPAWN_EGG
    - PIG_SPAWN_EGG
    - PILLAGER_SPAWN_EGG
    - PINK_BANNER
    - PINK_BED
    - PINK_DYE
    - PINK_TULIP
    - PINK_WOOL
    - PISTON
    - PODZOL
    - POISONOUS_POTATO
    - POLAR_BEAR_SPAWN_EGG
    - POPPY
    - PORKCHOP
    - POTATO
    - POTATOES
    - POTTED_ACACIA_SAPLING
    - POTTED_ALLIUM
    - POTTED_AZURE_BLUET
    - POTTED_BAMBOO
    - POTTED_BIRCH_SAPLING
    - POTTED_BLUE_ORCHID
    - POTTED_BROWN_MUSHROOM
    - POTTED_CACTUS
    - POTTED_CORNFLOWER
    - POTTED_DANDELION
    - POTTED_DARK_OAK_SAPLING
    - POTTED_DEAD_BUSH
    - POTTED_FERN
    - POTTED_JUNGLE_SAPLING
    - POTTED_LILY_OF_THE_VALLEY
    - POTTED_OAK_SAPLING
    - POTTED_ORANGE_TULIP
    - POTTED_OXEYE_DAISY
    - POTTED_PINK_TULIP
    - POTTED_POPPY
    - POTTED_RED_MUSHROOM
    - POTTED_RED_TULIP
    - POTTED_SPRUCE_SAPLING
    - POTTED_WHITE_TULIP
    - POTTED_WITHER_ROSE
    - POWERED_RAIL
    - PRISMARINE
    - PUFFERFISH
    - PUFFERFISH_BUCKET
    - PUFFERFISH_SPAWN_EGG
    - PUMPKIN
    - PUMPKIN_PIE
    - PUMPKIN_SEEDS
    - PURPLE_BANNER
    - PURPLE_BED
    - PURPLE_DYE
    - PURPLE_WOOL
    - RABBIT
    - RABBIT_FOOT
    - RABBIT_HIDE
    - RABBIT_SPAWN_EGG
    - RABBIT_STEW
    - RAIL
    - RAVAGER_SPAWN_EGG
    - RED_BANNER
    - RED_BED
    - RED_DYE
    - RED_MUSHROOM
    - RED_MUSHROOM_BLOCK
    - RED_SAND
    - RED_SANDSTONE
    - RED_TULIP
    - RED_WOOL
    - REDSTONE
    - REDSTONE_BLOCK
    - REDSTONE_LAMP
    - REDSTONE_ORE
    - REDSTONE_TORCH
    - REPEATER
    - ROSE_BUSH
    - SADDLE
    - SALMON
    - SALMON_BUCKET
    - SALMON_SPAWN_EGG
    - SAND
    - SANDSTONE
    - SCAFFOLDING
    - SCUTE
    - SEA_LANTERN
    - SEA_PICKLE
    - SEAGRASS
    - SHEARS
    - SHEEP_SPAWN_EGG
    - SHIELD
    - SILVERFISH_SPAWN_EGG
    - SKELETON_HORSE_SPAWN_EGG
    - SKELETON_SPAWN_EGG
    - SKULL_BANNER_PATTERN
    - SLIME_BALL
    - SLIME_BLOCK
    - SLIME_SPAWN_EGG
    - SMITHING_TABLE
    - SMOKER
    - SNOW_BLOCK
    - SNOWBALL
    - SOUL_SAND
    - SPECTRAL_ARROW
    - SPIDER_EYE
    - SPIDER_SPAWN_EGG
    - SPONGE
    - SQUID_SPAWN_EGG
    - STICK
    - STICKY_PISTON
    - STONECUTTER
    - STRAY_SPAWN_EGG
    - STRING
    - SUGAR
    - SUGAR_CANE
    - SUNFLOWER
    - SWEET_BERRIES
    - SWEET_BERRY_BUSH
    - TERRACOTTA
    - TNT
    - TNT_MINECART
    - TORCH
    - TOTEM_OF_UNDYING
    - TRADER_LLAMA_SPAWN_EGG
    - TRAPPED_CHEST
    - TRIDENT
    - TRIPWIRE
    - TRIPWIRE_HOOK
    - TROPICAL_FISH_BUCKET
    - TROPICAL_FISH_SPAWN_EGG
    - TURTLE_EGG
    - TURTLE_HELMET
    - TURTLE_SPAWN_EGG
    - VEX_SPAWN_EGG
    - VILLAGER_SPAWN_EGG
    - VINDICATOR_SPAWN_EGG
    - VINE
    - WALL_TORCH
    - WANDERING_TRADER_SPAWN_EGG
    - WATER_BUCKET
    - WHEAT
    - WHEAT_SEEDS
    - WHITE_BANNER
    - WHITE_BED
    - WHITE_DYE
    - WHITE_TULIP
    - WHITE_WOOL
    - WITCH_SPAWN_EGG
    - WOLF_SPAWN_EGG
    - WRITABLE_BOOK
    - YELLOW_BANNER
    - YELLOW_BED
    - YELLOW_DYE
    - YELLOW_GLAZED_TERRACOTTA
    - YELLOW_WOOL
    - ZOMBIE_SPAWN_EGG
    - ZOMBIE_VILLAGER_SPAWN_EGG
    nether:
    - BLAZE_SPAWN_EGG
    - CHISELED_QUARTZ_BLOCK
    - DIAMOND_HORSE_ARMOR
    - ELYTRA
    - ENDER_EYE
    - NETHER_BRICK
    - NETHER_BRICK_FENCE
    - NETHER_BRICK_SLAB
    - NETHER_BRICK_STAIRS
    - NETHER_BRICK_WALL
    - NETHER_BRICKS
    - NETHER_PORTAL
    - NETHER_QUARTZ_ORE
    - NETHER_STAR
    - NETHER_WART
    - NETHER_WART_BLOCK
    - NETHERRACK
    - QUARTZ
    - QUARTZ_BLOCK
    - QUARTZ_PILLAR
    - QUARTZ_SLAB
    - QUARTZ_STAIRS
    - RED_NETHER_BRICK_SLAB
    - RED_NETHER_BRICK_STAIRS
    - RED_NETHER_BRICK_WALL
    - RED_NETHER_BRICKS
    - WITHER_ROSE
    - WITHER_SKELETON_SKULL
    - WITHER_SKELETON_SPAWN_EGG
    - ZOMBIE_HORSE_SPAWN_EGG
    - ZOMBIE_PIGMAN_SPAWN_EGG
    end:
    - BLACK_SHULKER_BOX
    - BLUE_SHULKER_BOX
    - BROWN_SHULKER_BOX
    - CHORUS_FLOWER
    - CHORUS_FRUIT
    - CHORUS_PLANT
    - CYAN_SHULKER_BOX
    - DRAGON_BREATH
    - END_CRYSTAL
    - END_ROD
    - END_STONE
    - ENDERMAN_SPAWN_EGG
    - LIGHT_BLUE_SHULKER_BOX
    - LIGHT_GRAY_SHULKER_BOX
    - LIME_SHULKER_BOX
    - MAGENTA_SHULKER_BOX
    - ORANGE_SHULKER_BOX
    - PINK_SHULKER_BOX
    - POPPED_CHORUS_FRUIT
    - PURPLE_SHULKER_BOX
    - PURPUR_BLOCK
    - PURPUR_PILLAR
    - PURPUR_SLAB
    - PURPUR_STAIRS
    - RED_SHULKER_BOX
    - SHULKER_BOX
    - SHULKER_SHELL
    - SHULKER_SPAWN_EGG
    - WHITE_SHULKER_BOX
    - YELLOW_SHULKER_BOX

  # 天空网方块类型. 如果该方块不可用, 将用基岩替代.
  # 格式: 方块英文ID : 概率
  # 不同世界类型箱子中有不同的物品.
  # 主世界的组成方块. 不要设置太多的箱子, 箱子会引起卡顿.
  blocks:
    BROWN_MUSHROOM: 8
    STRIPPED_SPRUCE_LOG: 8
    SANDSTONE: 120
    RED_SAND: 20
    ACACIA_LOG: 20
    TNT: 1
    FERN: 4
    BOOKSHELF: 10
    PINK_TULIP: 8
    STRIPPED_ACACIA_LOG: 1
    OAK_WOOD: 19
    JUNGLE_SAPLING: 19
    WHITE_TULIP: 2
    CACTUS: 6
    SPRUCE_WOOD: 9
    BLUE_ORCHID: 1
    PUMPKIN: 9
    STRIPPED_ACACIA_WOOD: 1
    STRIPPED_BIRCH_LOG: 1
    WHEAT: 4
    STRIPPED_OAK_LOG: 1
    CHEST: 5
    GRASS_PATH: 7
    STRIPPED_BIRCH_WOOD: 1
    SPRUCE_LOG: 3
    STRIPPED_DARK_OAK_WOOD: 1
    RED_MUSHROOM: 8
    SPRUCE_SAPLING: 2
    REDSTONE_ORE: 2
    TALL_GRASS: 13
    DEAD_BUSH: 1
    DARK_OAK_SAPLING: 3
    GRASS_BLOCK: 200
    EMERALD_ORE: 5
    COAL_ORE: 70
    PETRIFIED_OAK_SLAB: 1
    SUNFLOWER: 3
    INFESTED_COBBLESTONE: 1
    DIORITE: 2
    STRIPPED_OAK_WOOD: 1
    FARMLAND: 7
    POPPY: 5
    DARK_OAK_WOOD: 18
    GOLD_ORE: 3
    DARK_OAK_LOG: 10
    CLAY: 5
    LILAC: 7
    DARK_PRISMARINE: 3
    STRIPPED_JUNGLE_LOG: 1
    PODZOL: 4
    ACACIA_LEAVES: 8
    GRASS: 100
    STRIPPED_SPRUCE_WOOD: 1
    LARGE_FERN: 8
    FIRE_CORAL_BLOCK: 1
    GRANITE: 50
    SAND: 50
    SUGAR_CANE: 4
    JUNGLE_LEAVES: 10
    JUNGLE_WOOD: 20
    BONE_BLOCK: 1
    RED_TULIP: 3
    SPAWNER: 5
    JUNGLE_LOG: 17
    MOSSY_COBBLESTONE: 1
    PRISMARINE: 3
    DANDELION: 16
    ALLIUM: 12
    ACACIA_WOOD: 16
    OAK_SAPLING: 11
    PEONY: 7
    LAVA: 5
    STRIPPED_DARK_OAK_LOG: 1
    OBSIDIAN: 1
    AZURE_BLUET: 1
    OXEYE_DAISY: 6
    DARK_OAK_LEAVES: 9
    GRAVEL: 20
    SEA_LANTERN: 1
    MELON: 15
    COBWEB: 7
    COARSE_DIRT: 17
    LAPIS_ORE: 6
    ACACIA_SAPLING: 17
    OAK_LOG: 10
    BIRCH_SAPLING: 8
    BEETROOTS: 9
    STRIPPED_JUNGLE_WOOD: 1
    BIRCH_LOG: 2
    BIRCH_WOOD: 16
    MYCELIUM: 2
    DIAMOND_ORE: 1
    RED_SANDSTONE: 19
    OAK_LEAVES: 4
    IRON_ORE: 10
    SPRUCE_LEAVES: 9
    SPONGE: 1
    SNOW_BLOCK: 1
    ORANGE_TULIP: 10
    BIRCH_LEAVES: 9
    ANDESITE: 90
    STONE: 180
    ROSE_BUSH: 8
  nether:
    # 是否生成下界
    generate: true
    # 下界天空网的组成方块
    # 尽量少设置岩浆和萤石 - 光线的计算
    # 会影响服务器的性能.
    blocks:
      SOUL_SAND: 90
      LAVA: 1
      NETHER_QUARTZ_ORE: 15
      MAGMA_BLOCK: 1
      NETHER_WART_BLOCK: 12
      GRAVEL: 10
      SPAWNER: 2
      CHEST: 15
      NETHER_WART: 19
      NETHERRACK: 200
      COBWEB: 7
      GLOWSTONE: 1
      RED_NETHER_BRICKS: 12
  end:
    # 是否生成下界
    generate: true
    # 下界天空网的方块组成. END_CRYSTAL(末影水晶) 已被禁用, 它会引发严重的性能问题.
    blocks:
      CHEST: 5
      END_ROD: 1
      CHORUS_PLANT: 2
      OBSIDIAN: 1
      END_STONE: 200
      GRAVEL: 10
      SPAWNER: 5
      PURPUR_BLOCK: 10
  # 是否为主世界分配生物群系 - 这将会影响某些方块和树木的类型.
  create-biomes: false
  # 为区块创建底面的概率. 底面位于 y=0.
  end-frame-probability: 0.1
  # 天空网世界的昵称. 可用于管理员指令. 必须为一个单词
  friendly-name: SkyGrid
  # 天空网世界的名称 - 不存在将会自动生成.
  # 对于下界和末地，这充当一个前缀
  world-name: skygrid-world
  # 天空网世界难度设置 - PEACEFUL, EASY, NORMAL, HARD
  # 其它插件可能会覆盖此设置
  difficulty: NORMAL
  # 起始坐标.
  start-x: 0
  start-z: 0
  # 天空网高度
  # 天空网最顶层的 y 坐标
  skygrid-height: 128
  # 出生点高度
  # 玩家默认出生点的 y 坐标. 不可大于上方所设值
  spawn-height: 128
  # 不同玩家之间的距离 (将被自动四舍五入为 16 的倍数)
  space-around-players: 1000
  # 玩家出生点的保护半径
  protection-range: 50
  # 天空网默认游戏模式. 比如, 玩家领取区域时会变为此游戏模式
  # 可用值: SURVIVAL, CREATIVE, ADVENTURE, SPECTATOR
  default-game-mode: SURVIVAL
  # 玩家一次最多能封禁多少人.
  # 权限: skygrid.ban.maxlimit.X
  # -1 = 无限
  ban-limit: -1
  # 生物白名单 - 这些生物将不会在玩家回家时被清除
  remove-mobs-whitelist:
  - GUARDIAN
  - ZOMBIE_VILLAGER
  - WITHER
  - ZOMBIFIED_PIGLIN
  # 世界属性.
  flags:
    OBSIDIAN_SCOOPING: true
    ENTER_EXIT_MESSAGES: true
    ISLAND_RESPAWN: true
    LIQUIDS_FLOWING_OUT: false
    REMOVE_END_EXIT_ISLAND: true
    REMOVE_MOBS: true
    TREES_GROWING_OUTSIDE_RANGE: false
    PREVENT_TELEPORT_WHEN_FALLING: false
    NATURAL_SPAWNING_OUTSIDE_RANGE: true
  # 默认保护设置.
  # 高于所设等级的玩家才可以完成该行为
  # 等级为: 游客 = 0, 成员 = 900, 区域主 = 1000
  default-protection-flags:
    HURT_ANIMALS: 500
    REDSTONE: 500
    BUCKET: 500
    LOCK: 0
    ENDER_PEARL: 500
    DOOR: 500
    FURNACE: 500
    ANVIL: 500
    MINECART: 500
    FISH_SCOOPING: 500
    FIRE: 500
    END_PORTAL: 500
    BREEDING: 500
    HURT_VILLAGERS: 500
    TNT: 500
    TURTLE_EGGS: 500
    FROST_WALKER: 500
    COLLECT_LAVA: 500
    LEVER: 500
    RIDING: 500
    HURT_MONSTERS: 500
    ARMOR_STAND: 500
    NAME_TAG: 500
    TRADING: 500
    EGGS: 500
    ITEM_DROP: 500
    NOTE_BLOCK: 500
    NETHER_PORTAL: 500
    CROP_TRAMPLE: 500
    ITEM_PICKUP: 500
    BREWING: 500
    DROPPER: 500
    COLLECT_WATER: 500
    BUTTON: 500
    FIRE_EXTINGUISH: 500
    BEACON: 500
    TRAPDOOR: 500
    PRESSURE_PLATE: 500
    PLACE_BLOCKS: 500
    ITEM_FRAME: 500
    CRAFTING: 500
    ENCHANTING: 500
    SHEARING: 500
    BOAT: 500
    BED: 500
    SPAWN_EGGS: 500
    MILKING: 500
    DISPENSER: 500
    GATE: 500
    EXPERIENCE_PICKUP: 500
    HOPPER: 500
    LEASH: 500
    MOUNT_INVENTORY: 500
    BREAK_BLOCKS: 500
    CHORUS_FRUIT: 500
    CONTAINER: 500
    JUKEBOX: 500
    POTION_THROWING: 500
  # 新保护区域的默认设置
  default-settings:
    PVP_END: false
    PVP_NETHER: false
    ANIMAL_SPAWN: true
    MONSTER_SPAWN: true
    FIRE_SPREAD: true
    PVP_OVERWORLD: false
  # 隐藏属性
  hidden-flags: []
  # 游客不能在保护区执行这些指令
  visitor-banned-commands: []
  # 掉落时禁止的指令
  # 需开启 PREVENT_TELEPORT_WHEN_FALLING 世界属性
  falling-banned-commands:
    - warp
    - spawn
area:
  # 默认队伍成员的最大值
  # 权限所设值不可低于此值.
  max-team-size: 4
  # 每个岛屿的合作者的最大人数
  # 赋予玩家 skygrid.coop.maxsize.<人数> 权限可覆盖此选项
  # 权限所设人数不得小于此值
  # Added since 1.13.0.
  max-coop-size: 4
  # 每个岛屿最多可以有多少个受信任玩家
  # 赋予玩家 skygrid.trust.maxsize.<人数> 权限可覆盖此选项
  # 权限所设人数不得小于此值
  # Added since 1.13.0.
  max-trusted-size: 4
  reset:
    # 玩家最多可以重置多少次岛屿 (可使用 /sgadmin clearresets <玩家名> 设置)
    # -1 意为无限, 0 为禁止重置.
    # 比如, 2 次重置表示玩家有 2 次重置机会或 3 次获得新岛屿的机会
    reset-limit: -1
    # 被踢出或主动离开队伍的玩家将会失去一次岛屿重置机会
    # 如果玩家的重置机会为 0, 且离开了队伍, 该玩家将不能再创建新岛屿, 只能加入其它队伍
    # 设为 true 可以避免玩家用不正常的方式使用队伍功能
    leavers-lose-reset: false
    # 保留被踢出玩家的背包物品.
    # 此项将覆盖 on-leave.inventory 设置.
    kicked-keep-inventory: false
    on-join:
      # 当玩家创建或加入一个岛屿时扩展是否重置这些项目
      # 重置金钱 - 若为 true, 将会将玩家的金钱重置为默认值
      # 推荐开启此功能, 但是如果你的服务器上还有其他玩法且你还想开启此功能
      # 请使用支持不同世界不同金钱的插件.
      money: false
      # 重置背包 - 若为 true, 玩家的背包将会被清空.
      # 注意: 如果你安装了 MultiInv 或其他相似的背包管理插件, 那些插件仍会在
      # 切换世界时更换玩家的背包.
      inventory: false
      # 重置血量 - 若为 true, 玩家将被治愈.
      health: true
      # 重置饥饿值 - 若为 true, 玩家将被喂饱.
      hunger: true
      # 重置经验值 - 若为 true, 玩家的经验值将被重置.
      exp: false
      # 重置末影箱 - 若为 true, 玩家末影箱中的物品将被清空.
      ender-chest: false
    on-leave:
      # 当玩家离开/被踢出一个岛屿时,扩展是否重置以下项目
      # 重置金钱 - 若为 true, 将会将玩家的金钱重置为默认值
      # 推荐开启此功能, 但是如果你的服务器上还有其他玩法且你还想开启此功能
      # 请使用支持不同世界不同金钱的插件.
      money: false
      # 重置背包 - 若为 true, 玩家的背包将会被清空.
      # 注意: 如果你安装了 MultiInv 或其他相似的背包管理插件, 那些插件仍会在
      # 切换世界时更换玩家的背包.
      inventory: false
      # 重置血量 - 若为 true, 玩家将被治愈.
      health: false
      # 重置饥饿值 - 若为 true, 玩家将被喂饱.
      hunger: false
      # 重置经验值 - 若为 true, 玩家的经验值将被重置.
      exp: false
      # 重置末影箱 - 若为 true, 玩家末影箱中的物品将被清空.
      ender-chest: false
  create-area-on-first-login:
    # 是否在玩家第一次进入服务器时自动创建该玩家的岛屿.
    # 若设为 true,
    #   * 当玩家第一次加入服务器时, 该玩家将被告知
    #     岛屿已创建.
    #   * 请确保你有一个叫 "default" 的模板: 此功能将用
    #     此模板创建岛屿.
    #   * 玩家不必执行指令即可创建岛屿.
    # 若设为 false, 此功能将被完全禁用.
    # 警告:
    #   * 如果你的服务器(单端)运行了多个游戏模式, 并且都
    #     开启了此功能, 所有游戏模式的岛屿都会被自动创建.
    #     但是, 玩家之后将被传送到哪个游戏模式是随机的.
    #   * 创建岛屿是比较占用服务器性能的, 请认真考虑是否启用此功能
    #     来相对的避免潜在的问题发生, 尤其是服务器人流量较大时.
    enable: false
    # 玩家登录服务器多少秒后, 岛屿将开始创建.
    # 若所设值 ≤ 0, 岛屿将在玩家登录时立即创建.
    # 建议此值不要大于 1 分钟(60 秒).
    delay: 5
    # 若玩家在上方所设的时间内离开了服务器
    # 是否停止岛屿的创建.
    # 若设为 true,
    #   * 若玩家在延缓期内离开了服务器，岛屿创建会停止.
    #     * 若玩家之后又加入了服务器，ta 不会再被视为新玩家，因此岛屿不会自动创建.
    #   * 若玩家在岛屿创建阶段离开了服务器, 岛屿会继续创建.
    # 若设为 false, 无论如何岛屿都会在延迟过后创建.
    # 若上方选项小于等于 0 ，此设置无任何效果.
    abort-on-logout: true
  commands:
    # 当玩家加入或创建岛屿时执行的指令.
    on-join: []
    # 当玩家离开岛屿、重置岛屿或被踢出岛屿时执行的指令.
    on-leave: []
  sethome:
    nether:
      allow: true
      require-confirmation: true
    the-end:
      allow: true
      require-confirmation: true
  deaths:
    # 是否记录死亡次数.
    counted: true
    # 最多记录的死亡次数. 死亡数可能会被其它扩展使用.
    max: 10
    # 当玩家加入一个队伍时，重置 ta 的死亡数
    team-join-reset: true
    # 是否在玩家创建新岛/重置岛屿时重置死亡数
    reset-on-new-island: true
    
protection:
  # 区域限制型生物.
  # 离开出生岛的这些生物将被移除.
  geo-limit-settings: []
  # 无敌游客设置. 这些伤害不会影响游客.
  # 留空以关闭无敌游客模式
  invincible-visitors: []
do-not-edit-these-settings:
  # 请勿修改此处
  reset-epoch: 0

